name: Build TrollStore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        brew install ldid
        brew install make
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip -d $GITHUB_WORKSPACE/theos/sdks
        rm master.zip
        
    - name: Update source URLs
      run: |
        sed -i '' 's|https://github.com/opa334/TrollStore/releases/latest/download/TrollStore.tar|http://124.70.142.143/TrollStore/releases/latest/download/TrollStore.tar|g' Shared/TSListControllerShared.m
        sed -i '' 's|https://github.com/opa334/ldid/releases/latest/download/ldid|http://124.70.142.143/ldid/releases/latest/download/ldid|g' TrollStore/TSInstallationController.m

    - name: Build project
      env:
        THEOS: ${{ github.workspace }}/theos
      run: |
        make clean
        make package
        
    - name: Create TrollStore.tar
      run: |
        cd packages
        tar -cvf TrollStore.tar *.deb
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: TrollStore
        path: packages/TrollStore.tar 
