name: Build TrollStore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # 安装基本依赖
    - name: Install dependencies
      run: |
        brew install ldid          # 安装签名工具
        brew install make          # 安装构建工具
        brew install openssl@3     # 安装 OpenSSL
        
    # 设置 Theos 开发环境
    - name: Setup Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git theos
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip
        mkdir -p theos/sdks
        mv sdks-master/* theos/sdks/
        rm -rf sdks-master master.zip
        
    # 设置 ChOma 签名工具
    - name: Setup ChOma
      run: |
        git clone https://github.com/opa334/ChOma.git
        cd ChOma/src
        # 修复文件名大小写问题
        find . -type f -name "*.h" -o -name "*.c" -o -name "*.m" | xargs sed -i.bak 's/"Fat\.h"/"FAT.h"/g'
        sed -i.bak 's/struct fat_header/struct FAT_header/g' FAT.h
        sed -i.bak 's/typedef struct fat_header FAT_header/typedef struct FAT_header FAT_header/g' FAT.h
        sed -i.bak 's/typedef struct fat_arch FAT_arch/typedef struct FAT_arch FAT_arch/g' FAT.h
        mv Fat.h FAT.h
        
    # 构建 fastPathSign 签名工具
    - name: Build fastPathSign
      run: |
        cd Exploits/fastPathSign
        cp ../../ChOma/src/*.h src/
        # 修复文件引用和函数调用
        find . -type f -name "*.h" -o -name "*.c" -o -name "*.m" | xargs sed -i.bak 's/"Fat\.h"/"FAT.h"/g'
        sed -i.bak 's/FAT \*fat/struct FAT \*fat/g' src/main.m
        sed -i.bak 's/update_load_commands_for_coretrust_bypass(macho, encodedSuperblobUnsigned, originalCodeSignatureSize, memory_stream_get_size(macho->stream))/update_load_commands_for_coretrust_bypass(macho, encodedSuperblobUnsigned, originalCodeSignatureSize)/' src/coretrust_bug.c
        make
        chmod +x fastPathSign
        
    # 更新源代码中的 URL 和修复依赖
    - name: Update source URLs and fix dependencies
      run: |
        # 修改主程序中的更新 URL
        sed -i.bak "s#https://github.com/opa334/TrollStore/releases/latest/download/TrollStore.tar#http://124.70.142.143/TrollStore/releases/latest/download/TrollStore.tar#g" Shared/TSListControllerShared.m
        # 修改 ldid 下载 URL
        sed -i.bak "s#https://github.com/opa334/ldid/releases/latest/download/ldid#http://124.70.142.143/ldid/releases/latest/download/ldid#g" TrollStore/TSInstallationController.m
        
        # 修改持续性助手中的更新 URL
        sed -i.bak "s#https://github.com/opa334/TrollStore/releases/latest/download/TrollStore.tar#http://124.70.142.143/TrollStore/releases/latest/download/TrollStore.tar#g" TrollHelper/TSHRootViewController.m
        
        # 列出所有 TrollHelper 相关文件
        find . -type f -name "*.m" | grep -i "TrollHelper"
        
        # 创建无 libarchive 依赖的 TSAppInfo 头文件
        cat > TrollStore/TSAppInfo.h << 'EOF'
        #import <Foundation/Foundation.h>
        @import UIKit;
        @interface TSAppInfo : NSObject
        {
            NSString* _path;
            BOOL _isArchive;
            NSString* _cachedAppBundleName;
            NSString* _cachedRegistrationState;
            NSDictionary* _cachedInfoDictionary;
            NSDictionary* _cachedInfoDictionariesByPluginSubpaths;
            NSDictionary* _cachedEntitlementsByBinarySubpaths;
            UIImage* _cachedPreviewIcon;
            int64_t _cachedSize;
        }
        - (instancetype)initWithIPAPath:(NSString*)ipaPath;
        - (instancetype)initWithAppBundlePath:(NSString*)bundlePath;
        - (NSError*)determineAppBundleName;
        - (NSError*)loadInfoDictionary;
        - (NSError*)loadEntitlements;
        - (NSError*)loadPreviewIcon;
        - (NSError*)sync_loadBasicInfo;
        - (NSError*)sync_loadInfo;
        - (void)loadBasicInfoWithCompletion:(void (^)(NSError*))completionHandler;
        - (void)loadInfoWithCompletion:(void (^)(NSError*))completionHandler;
        - (NSString*)displayName;
        - (NSString*)bundleIdentifier;
        - (NSString*)versionString;
        - (NSString*)sizeString;
        - (NSString*)bundlePath;
        - (NSString*)registrationState;
        - (UIImage*)iconForSize:(CGSize)size;
        - (NSAttributedString*)detailedInfoTitle;
        - (NSAttributedString*)detailedInfoDescription;
        - (BOOL)isDebuggable;
        - (void)log;
        @end
        EOF
        
        # 创建无 libarchive 依赖的 TSAppInfo 实现
        cat > TrollStore/TSAppInfo.m << 'EOF'
        #import "TSAppInfo.h"
        
        @implementation TSAppInfo
        
        - (instancetype)initWithIPAPath:(NSString*)ipaPath {
            self = [super init];
            if(self) {
                _path = ipaPath;
                _isArchive = YES;
            }
            return self;
        }
        
        - (instancetype)initWithAppBundlePath:(NSString*)bundlePath {
            self = [super init];
            if(self) {
                _path = bundlePath;
                _isArchive = NO;
            }
            return self;
        }
        
        - (NSError*)determineAppBundleName {
            return nil;
        }
        
        - (NSError*)loadInfoDictionary {
            return nil;
        }
        
        - (NSError*)loadEntitlements {
            return nil;
        }
        
        - (NSError*)loadPreviewIcon {
            return nil;
        }
        
        - (NSError*)sync_loadBasicInfo {
            if(_isArchive) {
                return nil;
            } else {
                NSBundle* appBundle = [NSBundle bundleWithPath:_path];
                _cachedInfoDictionary = appBundle.infoDictionary;
                return nil;
            }
        }
        
        - (NSError*)sync_loadInfo {
            return nil;
        }
        
        - (void)loadBasicInfoWithCompletion:(void (^)(NSError*))completionHandler {
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                NSError* error = [self sync_loadBasicInfo];
                if(completionHandler) {
                    completionHandler(error);
                }
            });
        }
        
        - (void)loadInfoWithCompletion:(void (^)(NSError*))completionHandler {
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                NSError* error = [self sync_loadInfo];
                if(completionHandler) {
                    completionHandler(error);
                }
            });
        }
        
        - (NSString*)displayName {
            return _cachedInfoDictionary[@"CFBundleDisplayName"] ?: _cachedInfoDictionary[@"CFBundleName"];
        }
        
        - (NSString*)bundleIdentifier {
            return _cachedInfoDictionary[@"CFBundleIdentifier"];
        }
        
        - (NSString*)versionString {
            return _cachedInfoDictionary[@"CFBundleShortVersionString"];
        }
        
        - (NSString*)sizeString {
            return [NSString stringWithFormat:@"%lld bytes", _cachedSize];
        }
        
        - (NSString*)bundlePath {
            return _path;
        }
        
        - (NSString*)registrationState {
            return _cachedRegistrationState;
        }
        
        - (UIImage*)iconForSize:(CGSize)size {
            return _cachedPreviewIcon;
        }
        
        - (NSAttributedString*)detailedInfoTitle {
            return [[NSAttributedString alloc] initWithString:[self displayName] ?: @""];
        }
        
        - (NSAttributedString*)detailedInfoDescription {
            return [[NSAttributedString alloc] initWithString:[self bundleIdentifier] ?: @""];
        }
        
        - (BOOL)isDebuggable {
            return NO;
        }
        
        - (void)log {
            NSLog(@"TSAppInfo: %@", self);
        }
        
        @end
        EOF
# 构建项目
    - name: Build project
      env:
        THEOS: ${{ github.workspace }}/theos
      run: |
        export PATH=$THEOS/bin:$PATH
        export THEOS_DEVICE_IP=127.0.0.1
        export THEOS_PLATFORM=ios
        
        # 编译主程序
        cd TrollStore
        
        # 创建 Makefile
        cat > Makefile << 'EOF'
        TARGET := iphone:clang:16.5:14.0
        INSTALL_TARGET_PROCESSES = TrollStore
        ARCHS = arm64
        
        TARGET_CODESIGN = ../Exploits/fastPathSign/fastPathSign
        
        include $(THEOS)/makefiles/common.mk
        
        APPLICATION_NAME = TrollStore
        
        TrollStore_FILES = $(wildcard *.m) $(wildcard ../Shared/*.m)
        TrollStore_FRAMEWORKS = UIKit CoreGraphics CoreServices CoreTelephony
        TrollStore_PRIVATE_FRAMEWORKS = Preferences MobileIcons MobileContainerManager
        TrollStore_LIBRARIES = archive
        TrollStore_CFLAGS = -fobjc-arc -I../Shared -I$(shell brew --prefix)/opt/libarchive/include
        TrollStore_CODESIGN_FLAGS = --entitlements entitlements.plist
        
        include $(THEOS_MAKE_PATH)/application.mk
        EOF
        
        # 移除 libarchive 依赖
        sed -i.bak 's/TrollStore_LIBRARIES = archive/TrollStore_LIBRARIES = /' Makefile
        
        make package FINALPACKAGE=1
        cp -r .theos/obj/TrollStore.app ../_build/
        cd ..
        
        # 编译持续性助手
        cd TrollHelper
        
        # 修改所有版本的更新 URL
        find . -type f -name "*.m" -o -name "*.h" | xargs sed -i.bak "s#https://github.com/opa334/TrollStore/releases/latest/download/TrollStore.tar#http://124.70.142.143/TrollStore/releases/latest/download/TrollStore.tar#g"
        find . -type f -name "*.m" -o -name "*.h" | xargs sed -i.bak "s#https://github.com/opa334/ldid/releases/latest/download/ldid#http://124.70.142.143/ldid/releases/latest/download/ldid#g"
        
        # 修改 RootHelper 中的 URL
        find ../RootHelper -type f -name "*.m" -o -name "*.h" | xargs sed -i.bak "s#https://github.com/opa334/TrollStore/releases/latest/download/TrollStore.tar#http://124.70.142.143/TrollStore/releases/latest/download/TrollStore.tar#g"
        find ../RootHelper -type f -name "*.m" -o -name "*.h" | xargs sed -i.bak "s#https://github.com/opa334/ldid/releases/latest/download/ldid#http://124.70.142.143/ldid/releases/latest/download/ldid#g"
        
        # 修改 Shared 目录中的 URL
        find ../Shared -type f -name "*.m" -o -name "*.h" | xargs sed -i.bak "s#https://github.com/opa334/TrollStore/releases/latest/download/TrollStore.tar#http://124.70.142.143/TrollStore/releases/latest/download/TrollStore.tar#g"
        find ../Shared -type f -name "*.m" -o -name "*.h" | xargs sed -i.bak "s#https://github.com/opa334/ldid/releases/latest/download/ldid#http://124.70.142.143/ldid/releases/latest/download/ldid#g"
        
        # 创建 Makefile
        cat > Makefile << 'EOF'
        export EMBEDDED_ROOT_HELPER ?= 0
        export LEGACY_CT_BUG ?= 0
        
        TARGET := iphone:clang:16.5:14.0
        INSTALL_TARGET_PROCESSES = TrollStorePersistenceHelper
        
        ifdef CUSTOM_ARCHS
        ARCHS = $(CUSTOM_ARCHS)
        else
        ARCHS = arm64
        endif
        
        ifneq ($(LEGACY_CT_BUG),1)
        TARGET_CODESIGN = ../Exploits/fastPathSign/fastPathSign
        endif
        
        include $(THEOS)/makefiles/common.mk
        
        APPLICATION_NAME = TrollStorePersistenceHelper
        
        TrollStorePersistenceHelper_FILES = $(wildcard *.m) $(wildcard ../Shared/*.m)
        TrollStorePersistenceHelper_FRAMEWORKS = UIKit CoreGraphics CoreServices CoreTelephony
        TrollStorePersistenceHelper_PRIVATE_FRAMEWORKS = Preferences MobileContainerManager
        TrollStorePersistenceHelper_CFLAGS = -fobjc-arc -I../Shared -I$(shell brew --prefix)/opt/libarchive/include
        
        ifeq ($(LEGACY_CT_BUG),1)
        TrollStorePersistenceHelper_CODESIGN_FLAGS = -Sentitlements.plist -K../legacy.p12
        TrollStorePersistenceHelper_CFLAGS += -DLEGACY_CT_BUG=1
        else
        TrollStorePersistenceHelper_CODESIGN_FLAGS = --entitlements entitlements.plist
        endif
        
        ifeq ($(EMBEDDED_ROOT_HELPER),1)
        TrollStorePersistenceHelper_CFLAGS += -DEMBEDDED_ROOT_HELPER=1
        TrollStorePersistenceHelper_FILES += $(wildcard ../RootHelper/*.m)
        TrollStorePersistenceHelper_LIBRARIES += archive
        TrollStorePersistenceHelper_PRIVATE_FRAMEWORKS += SpringBoardServices BackBoardServices FrontBoardServices
        endif
        
        include $(THEOS_MAKE_PATH)/application.mk
        EOF
        
        # 编译各个版本
        make clean
        make FINALPACKAGE=1 EMBEDDED_ROOT_HELPER=1 || true
        [ -f ".theos/obj/TrollStorePersistenceHelper.app/TrollStorePersistenceHelper" ] && cp .theos/obj/TrollStorePersistenceHelper.app/TrollStorePersistenceHelper ../_build/PersistenceHelper_Embedded
        
        make clean
        make FINALPACKAGE=1 EMBEDDED_ROOT_HELPER=1 LEGACY_CT_BUG=1 || true
        [ -f ".theos/obj/TrollStorePersistenceHelper.app/TrollStorePersistenceHelper" ] && cp .theos/obj/TrollStorePersistenceHelper.app/TrollStorePersistenceHelper ../_build/PersistenceHelper_Embedded_Legacy_arm64
        
        make clean
        make FINALPACKAGE=1 EMBEDDED_ROOT_HELPER=1 CUSTOM_ARCHS=arm64e || true
        [ -f ".theos/obj/TrollStorePersistenceHelper.app/TrollStorePersistenceHelper" ] && cp .theos/obj/TrollStorePersistenceHelper.app/TrollStorePersistenceHelper ../_build/PersistenceHelper_Embedded_Legacy_arm64e
        
        # 4. 普通版本 (放在最后编译)
        make clean
        make package FINALPACKAGE=1
        cp .theos/obj/TrollStorePersistenceHelper.app/TrollStorePersistenceHelper ../_build/TrollStorePersistenceHelper
        cd ..
        
        # 编译 trollstorehelper
        cd RootHelper
        
        # 创建 Makefile
        cat > Makefile << 'EOF'
        TARGET := iphone:clang:16.5:14.0
        ARCHS = arm64
        
        HELPER_NAME = trollstorehelper
        TARGET_CODESIGN = ../Exploits/fastPathSign/fastPathSign
        
        include $(THEOS)/makefiles/common.mk
        
        TOOL_NAME = $(HELPER_NAME)
        
        $(HELPER_NAME)_FILES = $(wildcard *.m) $(wildcard ../Shared/*.m) $(wildcard ../ChOma/src/*.c)
        $(HELPER_NAME)_FILES += ../Exploits/fastPathSign/src/coretrust_bug.c ../Exploits/fastPathSign/src/codesign.m
        
        $(HELPER_NAME)_CODESIGN_FLAGS = --entitlements entitlements.plist
        $(HELPER_NAME)_LDFLAGS = -L../ChOma/external/ios -lcrypto
        
        $(HELPER_NAME)_CFLAGS = -fobjc-arc -I../Shared $(shell pkg-config --cflags libcrypto) -I../ChOma/src -I../Exploits/fastPathSign/src -I$(shell brew --prefix)/opt/libarchive/include
        
        $(HELPER_NAME)_INSTALL_PATH = /usr/local/bin
        $(HELPER_NAME)_LIBRARIES = archive
        $(HELPER_NAME)_FRAMEWORKS = CoreTelephony
        $(HELPER_NAME)_PRIVATE_FRAMEWORKS = SpringBoardServices BackBoardServices MobileContainerManager FrontBoardServices RunningBoardServices
        
        include $(THEOS_MAKE_PATH)/tool.mk
        EOF
        
        make package FINALPACKAGE=1 || true
        [ -f ".theos/obj/trollstorehelper" ] && cp .theos/obj/trollstorehelper ../_build/
        cd ..
        
        # 5. 组装最终文件
        mkdir -p _build
        # 复制 trollstorehelper
        cp RootHelper/.theos/obj/trollstorehelper _build/
        # 复制 TrollStore
        cp -r TrollStore/.theos/obj/TrollStore.app _build/
        # 复制 PersistenceHelper
        cp TrollHelper/.theos/obj/TrollStorePersistenceHelper.app/TrollStorePersistenceHelper _build/
        # 确保所有二进制文件都正确签名
        for binary in ../_build/PersistenceHelper_Embedded* ../_build/trollstorehelper ../_build/TrollStorePersistenceHelper; do
            if [ -f "$binary" ]; then
                echo "Signing $binary"
                ldid -S"$THEOS/sdks/TrollStore.entitlements" "$binary"
            fi
        done
        
        # 为 TrollStore.app 签名
        if [ -d "../_build/TrollStore.app" ]; then
            echo "Signing TrollStore.app"
            ldid -S"$THEOS/sdks/TrollStore.entitlements" "../_build/TrollStore.app/TrollStore"
        fi
    # 上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore-Components
        path: |
          _build/trollstorehelper
          _build/TrollStore.app
          _build/TrollStorePersistenceHelper
          _build/PersistenceHelper_Embedded
          _build/PersistenceHelper_Embedded_Legacy_arm64
          _build/PersistenceHelper_Embedded_Legacy_arm64e 
