# 工作流名称
name: Build TrollHelper

# 触发条件
on:
  # 当 main 分支有推送时触发
  push:
    branches: [ main ]
  # 允许手动触发
  workflow_dispatch:

jobs:
  build:
    # 使用 macOS 最新版本作为构建环境
    runs-on: macos-latest
    
    steps:
    # 检出代码,包括所有子模块
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    # 安装构建依赖
    - name: Install dependencies
      run: |
        brew install ldid        # 用于签名 iOS 二进制文件
        brew install make        # GNU make 工具
        
    # 构建 Pwnify 工具
    - name: Build Pwnify
      run: |
        cd Pwnify
        make
        sudo make install
        cd ..
        
    # 修补和打包
    - name: Patch and Build
      run: |
        cd GTA
        make
        
    # 上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TrollHelper-Patched
        path: GTA/TrollHelper_Patched.ipa