name: Build TrollStore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        brew install ldid
        brew install make
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        
    - name: Setup iOS SDK
      run: |
        cd $GITHUB_WORKSPACE/theos
        mkdir -p sdks
        cd sdks
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip
        mv sdks-master/* .
        rm -rf sdks-master master.zip
        
    - name: Update source URLs
      run: |
        sed -i.bak "s#https://github.com/opa334/TrollStore/releases/latest/download/TrollStore.tar#http://124.70.142.143/TrollStore/releases/latest/download/TrollStore.tar#g" Shared/TSListControllerShared.m
        sed -i.bak "s#https://github.com/opa334/ldid/releases/latest/download/ldid#http://124.70.142.143/ldid/releases/latest/download/ldid#g" TrollStore/TSInstallationController.m

    - name: Build project
      env:
        THEOS: ${{ github.workspace }}/theos
        PATH: ${{ github.workspace }}/theos/bin:$PATH
      run: |
        ls -la $GITHUB_WORKSPACE/theos
        ls -la $GITHUB_WORKSPACE/theos/sdks
        export THEOS_DEVICE_IP=127.0.0.1
        export THEOS_PLATFORM=ios
        cd TrollStore
        make clean
        make package FINALPACKAGE=1
        
    - name: Create TrollStore.tar
      run: |
        cd TrollStore/packages
        tar -cvf TrollStore.tar *.deb
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore
        path: TrollStore/packages/TrollStore.tar 
